### ISSUE TITLE
Why does 'Pixel.js' not follow case sensitivity? 

### ISSUE THREAD

**Issue by deepio** [DDMAL/pixel_wrapper#30]
https://github.com/DDMAL/pixel_wrapper/blob/962072a931950be141b3e94a49b9235b7a879313/source/js/plugins/activate_wrapper.py#L3

https://github.com/DDMAL/pixel_wrapper/blob/962072a931950be141b3e94a49b9235b7a879313/source/js/plugins/activate_wrapper.py#L24

https://github.com/DDMAL/pixel_wrapper/blob/962072a931950be141b3e94a49b9235b7a879313/source/js/plugins/activate_wrapper.py#L49

Should be `Pixel.js` because the submodule below also has a capital for that folder?

https://github.com/DDMAL/Pixel.js/tree/c946a15f25b97287d320c6f68b2060b8cc9d0029

**Comment by deepio** [comment]
Commit: f81e2350b689c1a28bed7f14e9b969a7a7900f55

**Comment by EricHanLiu** [comment]
I think you're right, when I originally did this the submodule was lower-case because we had issues with the case sensitivity on my computer (@napulen), it might be best to change this for consistency sake

**Comment by deepio** [comment]
That's up to you, let me know what you decide to change when you do.

**Comment by napulen** [comment]
You can choose the name of the folder where your submodule gets added, just as you can choose the name of a repo you clone. Since we have issues with the case sensitivity of macOS filesystems, I have been suggesting we stick to "lowercase names" as much as we can. I would prefer to have a lowercase folder in the submodule than forcing pushes of the `.gitmodules` file because the filesystem messed it all up.

**Comment by deepio** [comment]
@napulen Its done, docker will install pixel the way you described. I deleted my branch.
