### ISSUE TITLE
Make a test script and lint. 

### ISSUE THREAD

**Issue by deepio** [DDMAL/pixel_wrapper#31]
The decision is up to you @EricHanLiu about which tools and how (I recommend jest), but I would like to see some unittests running and a codestyle enforcement. It is already partially implemented, as you can see below. 

https://github.com/DDMAL/pixel_wrapper/blob/8528ff2133063e0481537e74e61288e46d5e764e/package.json#L6-L7

https://github.com/DDMAL/pixel_wrapper/blob/8528ff2133063e0481537e74e61288e46d5e764e/.travis.yml#L8-L10

**Comment by EricHanLiu** [comment]
Todo list of things related to this issue:
- [ ] Fix all lint-detected syntax errors in Pixel.js and PixelWrapper
- [ ] Fix `JSHint failed` errors in source files (so that Travis succeeds)
- [ ] Implement unit tests using `jest` in Pixel.js submodule
  - [ ] Install `jest` properly
  - [ ] Implement tests in PixelWrapper also
- [ ] Fix vulnerabilities not solved by `npm audit fix`

**Comment by EricHanLiu** [comment]
Fixed lint syntax errors and ignored some lines to remove JSHint failure. 

Need to implement `Jest` properly with JavaScript that has classes and imports (`ES6`? Not sure what it's called, it's being transpiled by `Babel`).
- Seems jest needs a `.babelrc` config for projects that are compiled with `babel`, but not sure how to write this properly

**Comment by EricHanLiu** [comment]
travis works!!!

with a very basic jest test

**Comment by EricHanLiu** [comment]
So in the end it doesn't seem like it'll be at all trivial to implement unit tests in `Pixel`, since without instantiating some sort of `Diva` viewer (browser window) for it to properly initialize itself, `Pixel` (and consequently `PixelWrapper`) themselves cannot initialize properly. 

All three need to be initialized in order for the unit tests to be able to work on actual data and defined attributes. I've tried creating a 'mock' Diva instance which just has the attributes that are necessary for `PixelWrapper`, but this is impossible with how much dependence Pixel has, and the number of attributes that I'd have to mock

I've tried handling this by implement asynchronous tests, but it's difficult to wait on the termination of the `Diva` loader (which uses `fetch`). I've tried waiting a fixed amount of time using a JavaScript `pausecomp` (essentially a timed while loop), but even so the `Diva` viewer is not loaded afterwards, which leads me to believe it will never load without a viewport.

I have no idea how to implement some sort of viewport that's open, where `Diva, Pixel, PixelWrapper` are all instantiated, and **only then** begin to run the unit tests (and it seems too convoluted anyway). This would seem to be the only solution, to have a live, active `Diva` and `PixelPlugin` which we can run tests on, but I feel like this defeats the purpose of unit testing since we can just eye-test if everything works in about the same time

Since `PixelWrapper` is more or less done, there shouldn't be much need for unit testing. I don't believe much further work needs to (or will be) done, as it is already functionally sound. All the `lint` stuff has been fixed and cleaned up, so the project will also always be syntactically sound.
