### ISSUE TITLE
Enhancing performance of select region

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/pixel_wrapper#39]
The select-region layer only works from top-left to bottom-right. Sometimes, especially when one wants to select a region after pixels were already coloured with the other layers, it is easier to select the region by starting on another point different from the top-left coordinate of the region.

**Comment by EricHanLiu** [comment]
Will need to revert the background layer generation to loop over the entire page instead of over the selection regions. This should also fix the progress bar's accuracy (stalling while at 100% for up to a few minute).

Also need to implement the ability to select the entire page with a hotkey (ctrl/cmd-a) while in the selection region

**Comment by EricHanLiu** [comment]
Fixed in PR #40

**Comment by EricHanLiu** [comment]
Merged.
