### ISSUE TITLE
Generalize wrapper

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/pixel_wrapper#41]
As of now, Pixel in the Pixel wrapper is always displaying the Salzinnes manuscript metadata. This should be general to any manuscript (or display the resource filename)

See lines

https://github.com/DDMAL/pixel_wrapper/blob/develop/wrapper.py#L57
https://github.com/DDMAL/pixel_wrapper/blob/develop/wrapper.py#L65
https://github.com/DDMAL/pixel_wrapper/blob/develop/wrapper.py#L81-L83
https://github.com/DDMAL/pixel_wrapper/blob/develop/wrapper.py#L88-L91

**Comment by EricHanLiu** [comment]
The actual metadata references shouldn't change since the Diva parser needs these to be valid in order to run smoothly, but the actual `label` key (which is what is displayed in the diva-title) should be changed to the resource name.

There is no way to reference the resource name from the `inputs` dictionary, will have to find another way

**Comment by EricHanLiu** [comment]
So apparently the name of the resource isn't passed into Rodan, only the resource type and resource path.

The path isn't relevant even if we strip it, eg. for a file called 'imageportion.tiff' the path is
`/rodan/data/projects/8621e7eff70c4e23ab556d8eca1aaafb/resources/95ae643c8b904c7f8f78e95f9bb4fc0d/original_file.tiff`.

I think it's best to strip all visible references to the hardcoded manifest (but not the backend references) and just have a generic title or no title at all

**Comment by EricHanLiu** [comment]
Sticking with no title, looks a bit nicer style wise
